### ISSUE TITLE
Entites with funny characters in their identifiers

### ISSUE THREAD

**Issue by cthoyt** [NuriaQueralt/covid19-epidemiology-ontology#3]
It turns out that if you make RDF using this ontology, it might be serializable but then not parsable. This is the case for 5 (or potentially more) entities?

I will send a PR to change these IDs. More generally it would be nice if they could all be assigned more stable identifiers that are not linked to their labels.

```turtle
cemo:average_daily_number_of_new_infections_generated_per_case_(rt) rdfs:label "average daily number of new infections generated per case (rt)" ;
cemo:length_of_intensive_care_unit_(icu)_stay rdfs:label "length of icu stay" ;
cemo:number_of_cases_exposed_by_local_(one_or_cluster)_case rdfs:label "number of cases exposed by local (one or cluster) case" ;
cemo:points_of_interest_(pois) rdfs:label "points of interest (pois)" ;
cemo:predictive_value_positive_(pvp) rdfs:label "predictive value positive (pvp)" ;
```

**Comment by NuriaQueralt** [comment]
Hi @cthoyt ,

Thanks so much for checking this. This ontology is under development, so it is in our todos list to assign more stable identifiers.
